name: Generate Articles

on:
  push:
    paths:
      - 'articles/**'
  workflow_dispatch:

jobs:
  generate-articles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Generate articles.js
      run: node scripts/generate-articles.js
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add articles.js
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate articles.js from markdown files"
        git push 